#!/bin/bash

current_dir=$(pwd)
script_dir=$(dirname "$0")
if [ "$script_dir" = "." ]
then
script_dir="$current_dir"
fi

export ANT_HOME=${script_dir}/3p/ant
export PATH=${PATH}:${ANT_HOME}/bin

export category=$1
export target=do.${category}

ant_lib_extras=$script_dir/3p/ant/lib/extras

cd ..

ant -quiet -lib "$ant_lib_extras" -buildfile tasks/dependencies.xml ${target}
